[data]
    # Required
    data_dir = "../../../../suPAErnova_data"
    idr      = "IDR_eTmax.txt"
    mask     = "mask_info_wmin_wmax.txt"
    meta     = "meta.csv"

[pae]
    validation_frac = 0.1

    [pae.model]
        activation                 = "elu"
        architecture               = "dense"
        backend                    = "tf"
        batch_normalisation        = true
        dropout                    = 0.01
        encode_dims                = [256, 128]
        kernel_regulariser         = "L2"
        kernel_regulariser_penalty = 0.01
        loss                       = "MeanAbsoluteError"
        n_z_latents                = 3
        name                       = "Default"
        optimiser                  = "AdamW"
        physical_latents           = true
        scheduler                  = "ExponentialDecay"
        seperate_latent_training   = true
        seperate_z_latent_training = true

[nflow]
    [nflow.model]
        backend          = "tf"
        debug            = false
        n_hidden_units   = 8
        n_layers         = 12
        name             = "Default"
        physical_latents = true

[posterior]
    [posterior.model]
        backend="tch"
