[data]
    # Required
    data_dir = "../../../../suPAErnova_data"
    idr      = "IDR_eTmax.txt"
    mask     = "mask_info_wmin_wmax.txt"
    meta     = "meta.csv"

[pae]
    # Required
    backend = "tf"

    [pae.model]
        # === Required ===

        # --- Network Design ---
        architecture = "dense"
        encode_dims  = [256, 128]

        n_z_latents      = 3
        physical_latents = true

        # --- Training ---

        # These parameters can have custom functionality
        activation                 = "elu"
        kernel_regulariser         = "L2"
        kernel_regulariser_penalty = 0.01

        # Overfitting
        batch_normalisation = true
        dropout             = 0

        # Latent training
        seperate_latent_training   = true
        seperate_z_latent_training = true


        # === Optional ===
        colourlaw = ""
