[data]
    # Required
    data_dir = "../../../../suPAErnova_data"
    idr      = "IDR_eTmax.txt"
    mask     = "mask_info_wmin_wmax.txt"
    meta     = "meta.csv"

[pae]
    # === Required ===
    # --- Data ---
    validation_frac = 0

    # Base-case PAE model
    [pae.model]
        name = "Default"

        # === Required ===
        backend = "tf"

        # --- Network Design ---
        architecture = "dense"
        encode_dims  = [256, 128]

        n_z_latents      = 3
        physical_latents = true

        # --- Training ---
        # Overfitting
        batch_normalisation = true
        dropout             = 0

        # Latent training
        seperate_latent_training   = true
        seperate_z_latent_training = true

        # Batch size
        batch_size = 50

        # TF specific parameters
        activation                 = "elu"
        kernel_regulariser         = "L2"
        kernel_regulariser_penalty = 0.01
        loss                       = "MAE"
        optimiser                  = "AdamW"

    # Each model variant is provided with a different kfold.
    [[pae.variant]]
        name = "PhysicalLatents"

        n_z_latents = 0

    [[pae.variant]]
        name = "ZLatents"

        physical_latents = false

        # [[pae.variant]]
        #     name = "No latents"
        #
        #     n_z_latents      = 0
        #     physical_latents = false
