[data]
    # Required
    data_dir = "../../../../suPAErnova_data"
    idr      = "IDR_eTmax.txt"
    mask     = "mask_info_wmin_wmax.txt"
    meta     = "meta.csv"

[pae]
    # Required
    backend = "tf"

    [pae.model]
        # Required
        architecture = "dense"

        encode_dims = [256, 128]

        # Optional
        colourlaw = ""
