[project]
name = "supaernova-legacy"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Patrick Armstrong", email = "patrick.james.1998@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "matplotlib>=3.10.1",
]

[project.scripts]
supaernova-legacy = "supaernova_legacy:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
